{
 "title": "Docker Registry",
 "tags": [
  "docker",
  "registry",
  "internals"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "query_result(registry_http_in_flight_requests)"
   },
   {
    "name": "app",
    "query": "query_result(registry_http_in_flight_requests{kubernetes_namespace=\"$namespace\"})"
   },
   {
    "name": "instance",
    "query": "query_result(up{app=\"$app\"})"
   },
   { "name": "live_interval", "query": "1m, 2m, 5m, 10m, 15m, 30m" }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Live Cache Hit Rate",
   "type": "singlestat",
   "description": "The ratio of cache hits to cache requests right now",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{app=\"$app\", instance=~\"$instance\", type=\"Hit\"}[$live_interval])) / sum(rate(registry_storage_cache_total{app=\"$app\", instance=~\"$instance\", type=\"Request\"}[$live_interval]))"
    }
   ]
  },
  {
   "title": "Total Cache Hit Rate",
   "type": "singlestat",
   "description": "The ratio of cache hits to cache requests since start",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(registry_storage_cache_total{app=\"$app\", instance=~\"$instance\", type=\"Hit\"}) / sum(registry_storage_cache_total{app=\"$app\", instance=~\"$instance\", type=\"Request\"})"
    }
   ]
  },
  {
   "title": "Total Cache Requests",
   "type": "singlestat",
   "description": "The number of cache request received",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(registry_storage_cache_total{app=\"$app\", instance=~\"$instance\", type=\"Request\"})",
     "legendFormat": "{{ type }}: {{instance}}"
    }
   ]
  },
  {
   "title": "Total Hit Cache Requests",
   "type": "singlestat",
   "description": "The number of cache request received (hits)",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(registry_storage_cache_total{app=\"$app\", instance=~\"$instance\", type=\"Hit\"})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Total Missed Cache Requests",
   "type": "singlestat",
   "description": "The number of cache request received (miss)",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(registry_storage_cache_total{app=\"$app\", instance=~\"$instance\", type=\"Miss\"})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Average Resident Memory Usage",
   "type": "singlestat",
   "description": "Average Process Resident Memory Usage",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{instance=~\"$instance\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "CPU Usage: $instance",
   "type": "graph",
   "description": "Total User and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{app=\"registry\"}[5m]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Memory Usage: $instance",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{instance=~\"$instance\"})",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(process_virtual_memory_bytes{instance=~\"$instance\"})",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors: $instance",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_fds{job=\"$app\", instance=~\"$instance\"})",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  { "title": "Registry Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "HTTP Requests: $instance",
   "type": "graph",
   "description": "The HTTP requests summarized for all selected instances",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(handler)(ceil(rate(registry_http_requests_total{app=\"$app\", instance=~\"$instance\"}[5m])))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "In-Flight HTTP Requests: $instance",
   "type": "graph",
   "description": "The in-flight HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (handler) (registry_http_in_flight_requests{app=\"$app\", instance=~\"$instance\"})",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Registry Cache Requests Rate: $instance",
   "type": "graph",
   "description": "The rate of registry cache requests",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (ceil(rate(registry_storage_cache_total{app=\"$app\", instance=~\"$instance\"}[5m])))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Registry Action Latency: $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (action) (increase(registry_storage_action_seconds_sum{app=\"$app\", instance=~\"$instance\"}[2m]) * 1000)",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "HTTP Request Latencies in seconds (blob)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{app=\"$app\", handler=\"blob\"}[10m])"
    }
   ]
  },
  {
   "title": "Upload HTTP Request Latencies in seconds (base)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "avg(rate(registry_http_request_duration_seconds_bucket{app=\"$app\", handler=\"base\"}[10m]))"
    }
   ]
  },
  {
   "title": "Upload HTTP Request Latencies in seconds (blob_upload)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg(rate(registry_http_request_duration_seconds_bucket{app=\"$app\", handler=\"blob_upload\"}[10m]))"
    }
   ]
  },
  {
   "title": "Manifest HTTP Request Latencies in seconds (manifest)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{app=\"$app\", handler=\"manifest\"}[10m])"
    }
   ]
  },
  {
   "title": "Catalog HTTP Request Latencies in seconds (catalog)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "avg(rate(registry_http_request_duration_seconds_bucket{app=\"$app\", handler=\"catalog\"}[10m]))"
    }
   ]
  }
 ]
}