{
 "title": "Traefik",
 "description": "Traefik dashboard (data from prometheus on k8s) (based on Traefik by Thomas Cheronneau https://grafana.com/grafana/dashboards/4475)",
 "tags": [
  "prometheus",
  "traefik",
  "kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(traefik_service_request_duration_seconds_sum, service)"
   },
   { "name": "entrypoint", "query": "label_values(entrypoint)" }
  ]
 },
 "panels": [
  { "title": "Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average response time by service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{}) by (service) / sum(traefik_service_request_duration_seconds_count{}) by (service)",
     "legendFormat": " {{ service }}"
    }
   ]
  },
  {
   "title": "Requests by protocol for 5 min",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint =~ \"$entrypoint\"}[5m])) by (entrypoint)",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  },
  {
   "title": "Request rate by service for 5min",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[5m])) by (service)",
     "legendFormat": "{{  service }}"
    }
   ]
  },
  {
   "title": "Status code 200",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code=\"200\"}[1m])",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Others status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\",code!=\"200\"}[1m])",
     "legendFormat": "{{ method }} : {{code}}"
    }
   ]
  },
  { "title": "$service stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "$service response time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{service=~\"$service\"}) / sum(traefik_service_requests_total{service=~\"$service\"}) * 1000"
    }
   ]
  },
  {
   "title": "$service return code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "traefik_service_requests_total{exported_service=~\"$service\"}",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Total requests over 5min $service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{exported_service=~\"$service\"}[5m]))",
     "legendFormat": "Total requests $service"
    }
   ]
  }
 ]
}